# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-08 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_class', models.CharField(max_length=100)),
                ('role_name', models.CharField(max_length=100)),
            ],
        ),
    ]
